version: "3.9"

services:
  userservicedb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: ECSweden2022!
    volumes:
      - ./volumes/AuthDB:/var/opt/mssql/data

  bookservicedb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    ports:
      - 1434:1433
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: ECSweden2022!
    volumes:
      - ./volumes/BookDB:/var/opt/mssql/data

  loanservicedb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    ports:
      - 1435:1433
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: ECSweden2022!
    volumes: 
      - ./volumes/LoanDB:/var/opt/mssql/data

  authservice:
    # build: ./AuthService
    image: authservice
    restart: always
    ports:
      - 3000:80
    depends_on:
      - userservicedb

  bookservice:
    # build: ./BookService
    image: bookservice
    restart: always
    ports:
      - 3001:80
      - 3005:5555
    depends_on:
      - bookservicedb

  loanservice:
    # build: ./LoanService
    image: loanservice
    restart: always
    ports:
      - 3002:80      
    depends_on:
      - loanservicedb