version: "3.9"

services:
  userdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    ports:
      - 2433:1433
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: 2Secure*Password2
    volumes:
      - ./volumes/AuthDB:/var/opt/mssql/data

  bookdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    ports:
      - 2434:1433
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: 2Secure*Password21
    volumes:
      - ./volumes/BookDB:/var/opt/mssql/data

  loandb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    ports:
      - 2435:1433
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: 2Secure*Password22
    volumes: 
      - ./volumes/LoanDB:/var/opt/mssql/data

  authservice:
    # build: ./AuthService
    image: authservice
    restart: always
    ports:
      - 6001:80
    depends_on:
      - userdb

  bookservice:
    # build: ./BookService
    image: bookservice
    restart: always
    ports:
      - 6002:80
      - 6003:123
    depends_on:
      - bookdb

  loanservice:
    # build: ./LoanService
    image: loanservice
    restart: always
    ports:
      - 6004:80      
    depends_on:
      - loandb